name: Esegui test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Imposta Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installa le dipendenze
        run: npm install

      - name: Esegui i test
        run: npm test
